<?php

// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';

$client = new \Github\Client();
$repositories = $client->api('user')->repositories('manisiripella');

echo '<pre>';
print_r($repositories);

echo 'Letting the other person know that you care for him/her with your gestures.';
